name: Publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@bugfixes"
      - name: install deps
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: post install
        run: |
          npm rebuild
          npm run prepare --if-present
      - name: tests
        run: npm run test --if-present
      - name: version
        run: |
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/formats
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/express
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/i18n
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/loader
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/react
          npm --no-git-tag-version version ${GITHUB_REF##*/v} -workspace ./packages/utils
      - name: build
        run: npm run build
      - name: publish
        run: |
          npm publish ./packages/formats
          npm publish ./packages/express
          npm publish ./packages/i18n
          npm publish ./packages/loader
          npm publish ./packages/react
          npm publish ./packages/utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
